// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: 43inch

#include "ui.h"
#include "ui_helpers.h"
#include <Arduino.h>

extern String ssid;
extern String pwd;
extern int net_flag;

void wifi_button(lv_event_t *e)
{
	// Your code here

	ssid = "Makerfabs";
	pwd = "20160704";
	net_flag = 1;

	Serial.println(lv_textarea_get_text(ui_TextArea1));
	Serial.println(lv_textarea_get_text(ui_TextArea2));

	// delay(2000);
	Serial.println("[LOG]To screen 2");
	_ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
